##
##
## docker-compose down --volumes
version: '3.8'
services:
    repositorio:
        image: postgres:latest
        environment:
            - POSTGRES_USER=final
            - POSTGRES_PASSWORD=final
            - POSTGRES_DB=final
        restart: always
        ports:
            - 5432:5432
        volumes:
            #- database_data:
            - ./database/estructura.sql:/docker-entrypoint-initdb.d/db.sql
        logging:
            options:
                max-size: 10m
                max-file: "3"
    postgres:
        image: postgres:9.6
        #restart: always
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - ./database/db_airflow.sql:/docker-entrypoint-initdb.d/init.sql
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        build: ./airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./monitor:/home/airflow/monitor
            - ./airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    dashboard:
      #image: rocker/shiny:latest
      # para cambiar la imagen localmente
      build: ./dashboard
      depends_on:
          - postgres
      ports:
        - 3838:3838
      volumes:
      - ./server:/srv/shiny-server
      - ./logs:/var/log/shiny-server

